import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import Header from "./_components/header/Header";
import Footer from "./_components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextIntlClientProvider>
        <body className="min-h-full flex flex-col">
          <Header />
          <main className="flex-grow">{children}</main>
          <Footer />
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
